# Generated by Django 4.0.4 on 2022-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='last_name')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='gender')),
                ('school', models.CharField(max_length=50, verbose_name='school')),
                ('books', models.CharField(max_length=50, verbose_name='books')),
            ],
        ),
    ]
