# Generated by Django 4.0.4 on 2022-05-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionid', models.IntegerField(verbose_name='REGIONID')),
                ('school', models.CharField(max_length=150, verbose_name='school')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('principal', models.CharField(max_length=50, verbose_name='principal')),
                ('phone', models.CharField(max_length=8, verbose_name='phone')),
                ('address2', models.CharField(max_length=100, verbose_name='address2')),
            ],
        ),
    ]
