# Generated by Django 4.0.4 on 2022-05-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0002_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address2',
            field=models.CharField(max_length=100, null=True, verbose_name='address2'),
        ),
    ]
