# Generated by Django 4.0.4 on 2022-05-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0004_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='school',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='school',
            name='school',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagementapp.school'),
        ),
    ]
