# Generated by Django 4.0.4 on 2022-05-25 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0005_remove_book_id_remove_school_id_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagementapp.book'),
        ),
    ]
