# Generated by Django 4.0.4 on 2022-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0006_alter_student_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='school'),
        ),
    ]
