# Generated by Django 4.0.4 on 2022-05-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementapp', '0007_alter_student_books_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='books',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagementapp.book'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentmanagementapp.school'),
        ),
    ]
